require:
  - "mocha-suppress-logs"
spec:
  - "test/**/*.spec.js"
node-option:
  - "experimental-specifier-resolution=node"
# Stubbing in ts seems a nightmare.
# extension:
# - "ts"
# https://github.com/mochajs/mocha-examples/issues/47
# - "loader=ts-node/esm"
